<?php
require "init.php";

$PATIENT_ADM_NO = $_POST["PATIENT_ADM_NO"];
$PATIENT_SYMPTOMS = $_POST["PATIENT_SYMPTOMS"];
$PATIENT_MEDICAL_TESTS = $_POST["PATIENT_MEDICAL_TESTS"];
$PATIENT_MEDICINES_PRESCRIBED = $_POST["PATIENT_MEDICINES_PRESCRIBED"];
$PATIENT_MEDICAL_HISTORY_DATE_TIME_SHOW=$_POST["PATIENT_MEDICAL_HISTORY_DATE_TIME_SHOW"];
$PATIENT_MEDICAL_HISTORY_DATE_TIME_STORE=$_POST["PATIENT_MEDICAL_HISTORY_DATE_TIME_STORE"];
$sql_query = "INSERT INTO patient_medical_history VALUES('$PATIENT_ADM_NO','$PATIENT_SYMPTOMS','$PATIENT_MEDICAL_TESTS','$PATIENT_MEDICINES_PRESCRIBED','PATIENT_MEDICAL_HISTORY_DATE_TIME_SHOW','PATIENT_MEDICAL_HISTORY_DATE_TIME_STORE');";
if(mysqli_query($con,$sql_query))
{
	echo "Data Inserted";
}
else
{
	echo "Insertion Failed!!".mysqli_error($con);
}


?>